#!/bin/bash
go run ../src/main/main.go instance_0001.txt
go run ../src/main/main.go instance_0002.txt
go run ../src/main/main.go instance_0003.txt
go run ../src/main/main.go instance_0004.txt
go run ../src/main/main.go instance_0005.txt
go run ../src/main/main.go instance_0006.txt
go run ../src/main/main.go instance_0007.txt
go run ../src/main/main.go instance_0008.txt
go run ../src/main/main.go instance_0009.txt
go run ../src/main/main.go instance_0010.txt
go run ../src/main/main.go instance_0011.txt
go run ../src/main/main.go instance_0012.txt
go run ../src/main/main.go instance_0013.txt
go run ../src/main/main.go instance_0014.txt
go run ../src/main/main.go instance_0015.txt
go run ../src/main/main.go instance_0016.txt
go run ../src/main/main.go instance_0017.txt
go run ../src/main/main.go instance_0018.txt
go run ../src/main/main.go instance_0019.txt
go run ../src/main/main.go instance_0020.txt